### PR TITLE
Wrap any ActiveMQException inside an unchecked RPCException.

### LINKED ISSUE #698: RPC operations can throw UndeclaredThrowableException in some circumstances.
When an RPC client operation times out, Artemis throws an `ActiveMQConnectionTimedOutException` exception:
```java
2017-05-16T15:47:01,203 [WARN ] NodeTerminalView - Cash balance RPC failed: null
java.lang.reflect.UndeclaredThrowableException: null
        at com.sun.proxy.$Proxy27.getCashBalances(Unknown Source) ~[?:?]
        at net.corda.demobench.views.NodeTerminalView.pollCashBalances(NodeTerminalView.kt:217) [demobench-0.12-SNAPSHOT.jar:?]
        ...

Caused by: org.apache.activemq.artemis.api.core.ActiveMQConnectionTimedOutException: AMQ119014: Timed out after waiting 30,000 ms for response when sending packet 43
        at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:399) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:318) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at org.apache.activemq.artemis.core.protocol.core.impl.ActiveMQSessionContext.simpleCommit(ActiveMQSessionContext.java:328) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.commit(ClientSessionImpl.java:505) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at net.corda.client.rpc.internal.RPCClientProxyHandler.invoke(RPCClientProxyHandler.kt:209) ~[rpc-0.12-SNAPSHOT.jar:?]
        ... 8 more

```
However, this is a checked exception and none of the methods on `CordaRPCOps` declare it as thrown. This causes interoperability problems with Java, triggering an `UndeclaredThrowableException`.

I can reproduce this problem as follows:
- Launch DemoBench and create a simple notary node.
- Once the notary node has booted, suspend it using `kill -stop <pid>` (MacOS, Linux)
- Check `$HOME/demobench/demobench.log` for DemoBench's RPC client to notice that the node has stopped responding.

We need to wrap these checked Artemis exceptions inside unchecked exceptions.

### PR DESCRIPTION
**Pull request by chrisr3**
RPC operations can throw `ActiveMQException` instances when there is a problem. These are checked exceptions, but nothing on `CordaRPCOps` declares them as being thrown. This causes Java interoperability issues, so wrap any `ActiveMQException` with unchecked `RPCException`.

Fixes #698.

### CODE REVIEW

File: client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt [hunk 1]
```diff
@@ -209,6 +208,12 @@ class RPCClientProxyHandler(
                 it.session.commit()
             }
             return replyFuture.getOrThrow()
+        } catch (e: RuntimeException) {
+            // Already an unchecked exception, so just rethrow it
+            throw e
+        } catch (e: Exception) {
```
Comment (rick-r3) [inline client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt]: Hmmm.... I'm not so sure about throwing it, catching it, examining and re-throwing, since RPC could send an `Error` (possibly?) and it's hard to tell whether the catching of `Exception` involves client side raised conditions or just those coming from RPC.  Would it not be better to just sanitise the result of the future if it is an exception condition?

e.g. write a `Future.getOrThrowAsRuntimeOnly` rather than catching the result of `Future.getOrThrow`

or just examine the `Future` result here.

Comment (chrisr3) [inline client/rpc/src/main/kotlin/net/corda/client/rpc/internal/RPCClientProxyHandler.kt]: `Error` is a child of `Throwable` and so wouldn't be caught by either of these handlers. And I raised this issue because I noticed this exception in a DemoBench log file:
```
2017-05-16T15:09:01,269 [WARN ] NodeTerminalView - Cash balance RPC failed: null
java.lang.reflect.UndeclaredThrowableException: null
        at com.sun.proxy.$Proxy27.getCashBalances(Unknown Source) ~[?:?]
        at net.corda.demobench.views.NodeTerminalView.pollCashBalances(NodeTerminalView.kt:217) [demobench-0.12-SNAPSHOT.jar:?]
        at net.corda.demobench.views.NodeTerminalView.access$pollCashBalances(NodeTerminalView.kt:38) [demobench-0.12-SNAPSHOT.jar:?]
        at net.corda.demobench.views.NodeTerminalView$launchRPC$2.invoke(NodeTerminalView.kt:180) [demobench-0.12-SNAPSHOT.jar:?]
        at net.corda.demobench.views.NodeTerminalView$launchRPC$2.invoke(NodeTerminalView.kt:38) [demobench-0.12-SNAPSHOT.jar:?]
        at net.corda.demobench.rpc.NodeRPC$setupTask$1$run$1.run(NodeRPC.kt:41) [demobench-0.12-SNAPSHOT.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_131]
        at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_131]
Caused by: org.apache.activemq.artemis.api.core.ActiveMQConnectionTimedOutException: AMQ119014: Timed out after waiting 30,000 ms for response when sending packet 43
        at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:399) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:318) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at org.apache.activemq.artemis.core.protocol.core.impl.ActiveMQSessionContext.simpleCommit(ActiveMQSessionContext.java:328) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.commit(ClientSessionImpl.java:505) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at net.corda.client.rpc.internal.RPCClientProxyHandler.invoke(RPCClientProxyHandler.kt:209) ~[rpc-0.12-SNAPSHOT.jar:?]
```
i.e. `ActiveMQConnectionTimedOutException` being thrown by `it.session.commit()`. My proposed change turns this into:
```2017-05-16T17:18:43,201 [WARN ] NodeTerminalView - Cash balance RPC failed: AMQ119014: Timed out after waiting 30,000 ms for response when sending packet 43
net.corda.nodeapi.RPCException: AMQ119014: Timed out after waiting 30,000 ms for response when sending packet 43
        at net.corda.client.rpc.internal.RPCClientProxyHandler.invoke(RPCClientProxyHandler.kt:213) ~[rpc-0.12-SNAPSHOT.jar:?]
        at com.sun.proxy.$Proxy27.getCashBalances(Unknown Source) ~[?:?]
        at net.corda.demobench.views.NodeTerminalView.pollCashBalances(NodeTerminalView.kt:217) [demobench-0.12-SNAPSHOT.jar:?]
        at net.corda.demobench.views.NodeTerminalView.access$pollCashBalances(NodeTerminalView.kt:38) [demobench-0.12-SNAPSHOT.jar:?]
        at net.corda.demobench.views.NodeTerminalView$launchRPC$2.invoke(NodeTerminalView.kt:180) [demobench-0.12-SNAPSHOT.jar:?]
        at net.corda.demobench.views.NodeTerminalView$launchRPC$2.invoke(NodeTerminalView.kt:38) [demobench-0.12-SNAPSHOT.jar:?]
        at net.corda.demobench.rpc.NodeRPC$setupTask$1$run$1.run(NodeRPC.kt:41) [demobench-0.12-SNAPSHOT.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_131]
        at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_131]
Caused by: org.apache.activemq.artemis.api.core.ActiveMQConnectionTimedOutException: AMQ119014: Timed out after waiting 30,000 ms for response when sending packet 43
        at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:399) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.sendBlocking(ChannelImpl.java:318) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at org.apache.activemq.artemis.core.protocol.core.impl.ActiveMQSessionContext.simpleCommit(ActiveMQSessionContext.java:328) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.commit(ClientSessionImpl.java:505) ~[artemis-core-client-1.5.3.jar:1.5.3]
        at net.corda.client.rpc.internal.RPCClientProxyHandler.invoke(RPCClientProxyHandler.kt:209) ~[rpc-0.12-SNAPSHOT.jar:?]
        ... 8 more
```
This exception does not come from the `Future`.
